# Site settings
title: Jiongqian (Albert) Liang's Homepage
name: Jiongqian (Albert) Liang
url: "http://jiongqianliang.com"
#email: liang.420 AT osu.edu
description: Jiongqian's Personal Site
baseurl: "" # the subpath of your site, e.g. /blog/
scholar: 7KZ4FfwAAAAJ
linkedin: jiongqian-albert-liang-6538b557
resume: resume.pdf
logo_image: "/images/photo.jpg"
google-analytics_id: UA-40678383-2  # Google Analytics ID
highlighter: pygments
#twitter_username: waylau521  # Twitter ID
#github_username:  waylau # Github ID
#weibo_username: waylau521  # Weibo ID
#facebook_username: waylau521  # Facebook ID
#duoshuo_username: waylau # Duoshuo ID
#baidushare_id: 89860593 #  百度分享 ID
#google-analytics_id: UA-50593531-1  # Google Analytics ID
#rss_url: "/feed.xml"  # RSS 订阅 URL
# Build settings
#gems: [jekyll-paginate]
#markdown: rdiscount
#highlighter: rouge
#permalink: /:title/
#paginate: 8
#paginate_path: page/:num
 
